[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  APP_NAME = "Lighthouse Polytechnic University"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
